name: Run Auto-TVxml Script

on:
  schedule:
    - cron: '30 0 * * *'  # 在每天北京时间00:30运行

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 选择你的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests time re json

    - name: Run Auto-TVxml Script
      run: python Auto-TVxml.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tvxml.xml
        git commit -m "Update tvxml.xml"
        git push
